.TH "UNICORN" "3" "Dec 10th 2024" "Unicorn 0.8.0"
.SH NAME
uni_caseconvchk \- check case status
.SH LIBRARY
Embeddable Unicode Algorithms (libunicorn, -lunicorn)
.SH SYNOPSIS
.nf
.B #include <unicorn.h>
.PP
.BI "unistat uni_caseconvchk(unicaseconv " casing ", const void *" text ", unisize " length ", uniattr " attributes ", bool *" result ");"
.fi
.SH DESCRIPTION
Check if \f[I]text\f[R] with \f[I]attributes\f[R] is in the casing form \f[I]casing\f[R].
If it is, then the implementation writes \f[C]true\f[R] to \f[I]result\f[R] else \f[C]false\f[R].
.PP
If \f[I]length\f[R] is \f[C]-1\f[R], then the implementation assumes \f[I]text\f[R] null terminated.
.SH RETURN VALUE
.TP
UNI_OK
On success.
.TP
UNI_BAD_OPERATION
If \f[I]text\f[R] or \f[I]result\f[R] is \f[C]NULL\f[R].
.TP
UNI_FEATURE_DISABLED
If Unicorn was built without support for \f[I]casing\f[R].
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is published on the
.UR https://railgunlabs.com/unicorn
Railgun Labs website
.UE .
.SH LICENSING
Unicorn is distributed with its end-user license agreement (EULA).
Please review the agreement for information on terms & conditions for accessing or otherwise using Unicorn and for a DISCLAIMER OF ALL WARRANTIES.
