.TH "UNICORN" "3" "May 21st 2025" "Unicorn 1.0.6"
.SH NAME
uni_totitle \- simple title case mapping
.SH LIBRARY
Embeddable Unicode Algorithms (libunicorn, -lunicorn)
.SH SYNOPSIS
.nf
.B #include <unicorn.h>
.PP
.BI "unichar uni_totitle(unichar " c ");"
.fi
.SH DESCRIPTION
Return the simple title case mapping for the code point \f[I]c\f[R].
For the full title case mappings use \f[B]uni_caseconv\f[R](3) with \f[B]UNI_TITLE\f[R].
.PP
Support for simple title case mappings must be enabled in the JSON configuration file otherwise the function will always return \f[I]c\f[R].
.PP
.in +4n
.EX
{
    "characterProperties": [
        "Simple_Titlecase_Mapping"
    ]
}
.EE
.in
.SH RETURN VALUE
The simple title case mapping for \f[I]c\f[R].
.SH SEE ALSO
.BR uni_caseconv (3),
.BR unicaseconv (3),
.BR unichar (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is published on the
.UR https://railgunlabs.com/unicorn
Railgun Labs website
.UE .
.SH LICENSING
Unicorn is distributed with its end-user license agreement (EULA).
Please review the agreement for information on terms & conditions for accessing or otherwise using Unicorn and for a DISCLAIMER OF ALL WARRANTIES.
