.TH "UNICORN" "3" "May 21st 2025" "Unicorn 1.0.6"
.SH NAME
UNI_LITTLE \- little endian byte order
.SH LIBRARY
Embeddable Unicode Algorithms (libunicorn, -lunicorn)
.SH SYNOPSIS
.nf
.B #include <unicorn.h>
.PP
.B #define UNI_LITTLE 0x20u
.fi
.SH DESCRIPTION
Text attribute bit flag that indicates the text is encoded in little endian byte order.
It's incompatible with the \f[B]UNI_BIG\f[R](3) flag.
.PP
The flag is intended for use with \f[B]UNI_UTF16\f[R](3) and \f[B]UNI_UTF32\f[R](3).
It has no effect when used with \f[B]UNI_UTF8\f[R](3) or \f[B]UNI_SCALAR\f[R](3).
.SH SEE ALSO
.BR UNI_BIG (3),
.BR UNI_UTF16 (3),
.BR UNI_UTF32 (3),
.BR UNI_UTF8 (3),
.BR UNI_SCALAR (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is published on the
.UR https://railgunlabs.com/unicorn
Railgun Labs website
.UE .
.SH LICENSING
Unicorn is distributed with its end-user license agreement (EULA).
Please review the agreement for information on terms & conditions for accessing or otherwise using Unicorn and for a DISCLAIMER OF ALL WARRANTIES.
