.TH "UNICORN" "3" "Jan 14th 2026" "Unicorn 1.3.2"
.SH NAME
uni_getucdversion \- unicode standard version
.SH LIBRARY
Embeddable Unicode Algorithms (libunicorn, -lunicorn)
.SH SYNOPSIS
.nf
.B #include <unicorn.h>
.PP
.BI "void uni_getucdversion(int32_t *" major ", int32_t *" minor ", int32_t *" patch ");"
.fi
.SH DESCRIPTION
Writes the major, minor, and patch version of the Unicode Standard to \f[I]major\f[R], \f[I]minor\f[R], and \f[I]patch\f[R], respectively.
Null arguments are ignored.
.SH EXAMPLES
This example prints the major, minor, and patch version of the Unicode Standard implemented by the library to stdout.
.PP
.in +4n
.EX
#include <unicorn.h>
#include <stdio.h>

int main(void)
{
    int32_t major, minor, patch;
    uni_getucdversion(&major, &minor, &patch);
    printf("%d.%d.%d", major, minor, patch);
    return 0;
}
.EE
.in
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is published on the
.UR https://railgunlabs.com/unicorn
Railgun Labs website
.UE .
.SH LICENSING
Unicorn is distributed with its end-user license agreement (EULA).
Please review the agreement for information on terms & conditions for accessing or otherwise using Unicorn and for a DISCLAIMER OF ALL WARRANTIES.
