.TH "UNICORN" "3" "Jan 27th 2025" "Unicorn 1.0.4"
.SH NAME
UNI_SCALAR \- unicode scalar value
.SH LIBRARY
Embeddable Unicode Algorithms (libunicorn, -lunicorn)
.SH SYNOPSIS
.nf
.B #include <unicorn.h>
.PP
.B #define UNI_SCALAR 0x1u
.fi
.SH DESCRIPTION
Text attribute bit flag that indicates the text is encoded as Unicode scalar values.
This is a pseudo-encoding that uses the \f[B]unichar\f[R](3) type for storage.
.PP
Unicode scalars are not the same as code points.
The former excludes surrogate characters whereas the latter does not.
.SH SEE ALSO
.BR unichar (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is published on the
.UR https://railgunlabs.com/unicorn
Railgun Labs website
.UE .
.SH LICENSING
Unicorn is distributed with its end-user license agreement (EULA).
Please review the agreement for information on terms & conditions for accessing or otherwise using Unicorn and for a DISCLAIMER OF ALL WARRANTIES.
